apiVersion: watcher.openstack.org/v1beta1
kind: WatcherDecisionEngine
metadata:
  labels:
    app.kubernetes.io/name: watcherdecisionengine
    app.kubernetes.io/instance: watcherdecisionengine-sample
    app.kubernetes.io/part-of: watcher-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: watcher-operator
  name: watcherdecisionengine-sample
spec:
  secret: "watcher"
  memcachedInstance: "memcached"
  serviceAccount: "watcher-watcher"
